name: kasirrrrr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Kebutuhan Aplikasi Anda
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  fl_chart: ^0.68.0 
  intl: ^0.19.0
  collection: ^1.18.0
  mime: ^1.0.4
  blue_thermal_printer: ^1.2.3 
  dotted_border: ^2.1.0
  cupertino_icons: ^1.0.8

  # --- DEPENDENSI UNTUK EKSPOR LAPORAN (DIPERBARUI) ---
  pdf: ^3.10.8 
  excel: ^4.0.2 
  path_provider: ^2.1.3 
  permission_handler: ^11.3.1 

  # PERBAIKAN: Menggunakan versi open_file_plus yang valid dan terbaru
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  # Konfigurasi flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

